name = "Origins Pandora"
author = "ImUrX"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f63cd1d4c3140695a59eb03767ff22a5b9225f5deb39a6c04099895508cd2e80"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
