name = "Origins Pandora"
author = "ImUrX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09e5f17067dacd9951b1ad0d1ad27aa4e8c238ab44d354c6f34e4a4bc7fbc46e"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
