name = "Origins Pandora"
author = "ImUrX"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e47d04dfb80fc495757f6164edee4f0250448c8839272ab0c01def7ccafe0e71"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
