name = "Origins Pandora"
author = "ImUrX"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "390c5c352428908dac044d418bdc118397f2e4ba0013912f55b19d024805612f"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
