name = "Origins Pandora"
author = "ImUrX"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9bd01b23eba85fa3d55dc37c006f4087f2f60de23eff862d262d5387a8639af"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
