name = "Origins Pandora"
author = "ImUrX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "648a57aca8c8f282d214c27157dcb4fc4aee0e7cdd6d5028a5ab9e535a89a119"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
