name = "Origins Pandora"
author = "ImUrX"
version = "1.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed860f3d955c065402a11150c32bc68c02cea22b0a8a1b8f7d86c41d9d4fd06f"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
