name = "Origins Pandora"
author = "ImUrX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12186f9092b1d6b6c1087459b8382a1be92106296bd4a270e97529e23cf09a82"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
