name = "Origins Pandora"
author = "ImUrX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b43d86a84caeac2723a5f8202d57a8dedbd6ba262e54c7f571712d24e2c448a1"

[versions]
fabric = "0.14.8"
minecraft = "1.19"

[options]
acceptable-game-versions = ["1.19-pre3"]
