name = "Origins Pandora"
author = "ImUrX"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "954c33c7f68c33dfc46147d24883b6411738a8ff942fd0d0e3f687bb0a3e0280"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
