name = "Origins Pandora"
author = "ImUrX"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b0a305049fd99296cb61f733b3d417a402f54e86dff278f754afb28a3e4019a"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
