name = "Origins Pandora"
author = "ImUrX"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74e7b2bb83ef6397f916d679568f8975cd3a9ff9c4565da189eee28846a5bc01"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
